version: '3.7'
services:
  postgres:
    image: postgres:11
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: todo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: postgres
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 7000:8080